name: sensitivity_analysis_ices
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - blosc=1.21.6=hf7d4471_0
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - c-blosc2=2.12.0=h80c7b02_0
  - ca-certificates=2025.7.15=h06a4308_0
  - colorcet=3.1.0=py311h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - freetype=2.13.3=h4a9f257_0
  - hdf5=1.12.1=h2b7332f_3
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.31.0=pyh707e725_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcurl=8.14.1=hc1efc7f_1
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.10=py311h5eee18b_0
  - mkl_random=1.2.7=py311ha02d727_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py311hf4471f9_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.17=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py311h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=py311h06a4308_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pytables=3.9.2=py311h9d13977_0
  - python=3.11.10=he870216_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - seaborn=0.13.2=py311h06a4308_3
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zlib-ng=2.0.7=h5eee18b_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - attrs==24.2.0
      - cattrs==24.1.2
      - cfgv==3.4.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dill==0.3.9
      - distlib==0.3.9
      - docstring-to-markdown==0.15
      - execnet==2.1.1
      - filelock==3.16.1
      - fonttools==4.54.1
      - identify==2.6.3
      - iniconfig==2.0.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - multiprocess==0.70.17
      - mypy==1.15.0
      - mypy-extensions==1.1.0
      - nodeenv==1.9.1
      - nptyping==2.5.0
      - packaging==24.1
      - pandas==1.5.3
      - pandas-stubs==2.2.3.250308
      - pathos==0.3.3
      - pillow==10.4.0
      - pluggy==1.5.0
      - pox==0.3.5
      - ppft==1.7.6.9
      - pre-commit==4.0.1
      - pytest==8.3.3
      - pytest-xdist==3.6.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - ruff==0.9.3
      - scipy==1.14.0
      - shapely==2.1.1
      - six==1.16.0
      - tqdm==4.67.1
      - types-pytz==2025.2.0.20250516
      - virtualenv==20.28.0
